#include <stdio.h>
#include <glib.h>
#include <sys/types.h>
#include <unistd.h>
#include <gio/gio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <string.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <arpa/inet.h>
#include <mysql.h>
#include <sodium.h>
#include <zlib.h>
#include <syslog.h>
#include <stdio.h>
#include <errno.h>
#include <time.h>
#include <stdarg.h>
#include <string.h>
//#include <print_logs.h>